"""Curated wellness content for the Solo Expression suggestions.

A large bank (not a single canned response) that ``solo_service`` samples from at
random per request, keyed by the seven mood categories. Everything here is
general self-help / grounding material, not clinical advice.

Video links are YouTube search URLs (always resolve, never 404) so the deployed
app never shows a dead link; the ``title`` is what the user sees.
"""

from app.schemas.solo_schema import SoloEmotion


def _yt(query: str) -> str:
    return "https://www.youtube.com/results?search_query=" + query.replace(" ", "+")


WELLNESS_CONTENT: "dict[SoloEmotion, dict[str, list]]" = {
    "stress": {
        "videos": [
            {"title": "Box breathing (4-4-4-4), guided 5 minutes", "url": _yt("box breathing 4 4 4 4 guided 5 minutes")},
            {"title": "10-minute stress-relief body scan", "url": _yt("10 minute stress relief body scan meditation")},
            {"title": "Progressive muscle relaxation, full session", "url": _yt("progressive muscle relaxation guided")},
            {"title": "Quick desk reset for a stressful workday", "url": _yt("quick desk stretch reset stress 5 minutes")},
        ],
        "quotes": [
            "You don't have to do everything at once - just the next kind step.",
            "Even when you feel behind, your effort still counts.",
            "Breathe first. Then choose one small thing to steady yourself.",
            "Pressure is real, but it is not the whole story of who you are.",
            "You can carry a lot and still put some of it down for a minute.",
            "Slow is still moving.",
            "A calmer mind usually starts with a calmer body.",
            "You are allowed to protect your energy.",
            "Done is kinder than perfect today.",
            "One task, one breath, one moment at a time.",
        ],
        "exercises": [
            "Two-minute box breathing: inhale 4, hold 4, exhale 4, hold 4 - repeat 6 cycles.",
            "Brain dump: write the top 5 worries, then circle the one you can influence today.",
            "Shoulders and jaw release: 5 slow shoulder rolls, unclench the jaw, exhale longer than you inhale.",
            "Single-tasking sprint: set a timer for 15 minutes and do only one thing.",
            "Physiological sigh: two inhales through the nose, one long exhale through the mouth, 5 times.",
            "Feet on the floor: press both feet down, feel the contact, take 5 slow breaths.",
            "Worry window: give yourself 10 minutes to worry on paper, then close the notebook.",
            "Cool-down walk: 5 minutes outside, no phone, notice 3 things you can hear.",
            "Hand on chest, hand on belly: breathe so only the lower hand moves, for 1 minute.",
        ],
        "tips": [
            "Pick one priority for the next hour and let the rest wait.",
            "Lower the bar: define 'good enough' for today in one sentence.",
            "If your body is tense, fix the body first, then think.",
            "Batch the small stuff into one 20-minute block instead of all day.",
            "Say no to one optional thing this week.",
            "Drink a glass of water before you decide anything feels urgent.",
            "Put your phone in another room while you do the hard task.",
            "Ask 'will this matter in a week?' before you spend energy on it.",
            "Schedule a 10-minute break the way you'd schedule a meeting.",
        ],
    },
    "anxiety": {
        "videos": [
            {"title": "5-4-3-2-1 grounding exercise, guided", "url": _yt("5 4 3 2 1 grounding exercise guided anxiety")},
            {"title": "Extended-exhale breathing for anxiety", "url": _yt("extended exhale breathing anxiety guided")},
            {"title": "10-minute anxiety-relief meditation", "url": _yt("10 minute anxiety relief meditation")},
            {"title": "Calm the nervous system, gentle practice", "url": _yt("calm nervous system vagus nerve exercise")},
        ],
        "quotes": [
            "Anxiety is loud, but it isn't always accurate.",
            "You can be scared and still be capable.",
            "Let the feeling be present without letting it drive.",
            "A thought is not a fact, even a very convincing one.",
            "You have handled hard moments before. This is another one.",
            "Worry is not preparation.",
            "You are safe enough, right now, to take one breath.",
            "Uncertainty is uncomfortable, not dangerous.",
            "You can do the next small thing while still feeling nervous.",
            "This feeling will crest and pass, like every one before it.",
        ],
        "exercises": [
            "5-4-3-2-1 grounding: name 5 things you see, down to 1 thing you taste.",
            "Worry container: set a 10-minute timer to worry on paper, then stop when it ends.",
            "Label the sensation: 'tight chest', 'fast thoughts' - name it, then breathe out slowly.",
            "4-7-8 breath: inhale 4, hold 7, exhale 8, for 4 rounds.",
            "Temperature shift: hold something cold or splash cool water on your face for 30 seconds.",
            "Name the story: 'I'm telling myself that...' then 'a kinder version is...'.",
            "Feet and hands: wiggle your toes, press your fingertips together, come back to the room.",
            "Two-column check: write 'what I fear' next to 'what is most likely'.",
            "Slow count: breathe out while counting down from 10, twice.",
        ],
        "tips": [
            "Ask: 'Is this a possibility or a certainty?' Treat it like a possibility.",
            "Reduce inputs for 10 minutes (notifications, scrolling, caffeine).",
            "Choose the smallest next action and do it imperfectly.",
            "Move your body for 2 minutes - anxious energy needs somewhere to go.",
            "Postpone the decision if you can; anxious brains predict badly.",
            "Tell one person 'I'm feeling anxious' - naming it out loud shrinks it.",
            "Keep your blood sugar steady; hunger mimics anxiety.",
            "Write the worst case, the best case, and the likely case.",
            "Come back to your senses: what can you actually see and hear right now?",
        ],
    },
    "sadness": {
        "videos": [
            {"title": "Self-compassion break, guided", "url": _yt("self compassion break guided meditation kristin neff")},
            {"title": "Gentle mood-lift walk, follow along", "url": _yt("gentle walking meditation mood lift")},
            {"title": "10-minute meditation for low mood", "url": _yt("10 minute meditation for sadness low mood")},
            {"title": "Soothing music for a heavy day", "url": _yt("calm soothing instrumental music for sadness")},
        ],
        "quotes": [
            "Sadness asks for gentleness, not speed.",
            "You're allowed to take up space with what you feel.",
            "Small care is still real care.",
            "You don't have to earn rest.",
            "Feeling low is not a personal failure.",
            "Heavy days pass, even when it's hard to believe.",
            "Be as kind to yourself as you would be to a friend.",
            "You can grieve something and still keep going.",
            "It's okay to do less today.",
            "Reaching out is a strength, not a burden.",
        ],
        "exercises": [
            "Compassion note: write 3 lines to yourself as if to a friend.",
            "Tiny activation: stand up, drink water, open a window, take 10 slow steps.",
            "Mood check: 'What would make today 2% easier?' Do only that.",
            "Name one small thing that went okay, however minor.",
            "Sunlight or bright light for 5 minutes, near a window is fine.",
            "Send one message: 'Could we talk for 5 minutes?'",
            "Warm reset: a warm drink or a warm shower, slowly.",
            "Put on one song you love and just listen to it.",
            "Write down what you'd want someone to say to you right now, then read it back.",
        ],
        "tips": [
            "Don't negotiate with yourself - do a tiny caring action first, feelings can follow.",
            "Reach for connection: a short message counts.",
            "Make your environment softer (light, warm drink, music).",
            "Lower today's to-do list to the essentials plus one kind thing.",
            "Move gently - a short walk shifts mood chemistry.",
            "Eat something regular even if you're not hungry.",
            "Limit doomscrolling; it deepens the dip.",
            "Plan one small thing to look forward to tomorrow.",
            "If this lasts more than two weeks, consider talking to a professional.",
        ],
    },
    "happiness": {
        "videos": [
            {"title": "Savoring practice, guided", "url": _yt("savoring positive experience guided practice")},
            {"title": "3-minute gratitude meditation", "url": _yt("3 minute gratitude meditation")},
            {"title": "Loving-kindness meditation, short", "url": _yt("short loving kindness meditation")},
            {"title": "Feel-good movement break", "url": _yt("feel good 5 minute movement break")},
        ],
        "quotes": [
            "This moment matters - let yourself actually receive it.",
            "Joy grows when you notice it on purpose.",
            "Keep what works. Repeat what helps.",
            "Good days are data too - notice what built this one.",
            "You are allowed to feel good without earning it.",
            "Savour it slowly; it counts more that way.",
            "Share the win - it doubles.",
            "Let this be a memory you can return to.",
            "Small joys are still joys.",
            "Notice who and what helped, and thank them.",
        ],
        "exercises": [
            "Savoring: replay one good moment for 20 seconds, noticing colours, sounds, body feelings.",
            "Share it: text one person a simple win you noticed today.",
            "Gratitude specifics: write one thing you appreciate and why it mattered.",
            "Anchor it: take a photo or write one line so you can revisit this later.",
            "Pay it forward: do one small kind thing for someone while the mood is good.",
            "Name the recipe: what three things helped create this feeling?",
            "Stretch and smile for 30 seconds - let the body join in.",
            "Plan a repeat: put one of today's good things on the calendar.",
            "Write a 'good day' note to your future self.",
        ],
        "tips": [
            "Capture the win: write one sentence so you can return to it later.",
            "Celebrate without minimising - no 'but...' for 60 seconds.",
            "Turn it into a habit: what helped today that you can repeat tomorrow?",
            "Tell someone; positive news shared tends to last longer.",
            "Protect the conditions that made this possible (sleep, breaks, people).",
            "Do a little less than you feel able to, so the momentum lasts.",
            "Notice the ordinary parts of today that were fine, not just the highlight.",
        ],
    },
    "anger": {
        "videos": [
            {"title": "Cool down fast: breath and body for anger", "url": _yt("cool down anger breathing exercise fast")},
            {"title": "Progressive muscle relaxation for tension", "url": _yt("progressive muscle relaxation anger tension")},
            {"title": "10-minute meditation to release frustration", "url": _yt("10 minute meditation release frustration anger")},
            {"title": "Grounding after a heated moment", "url": _yt("grounding technique after argument calm down")},
        ],
        "quotes": [
            "Anger often protects something important - listen without exploding.",
            "You can set boundaries without burning bridges.",
            "Strong feelings deserve skillful handling.",
            "You can be angry and still choose how you act.",
            "The goal isn't to feel nothing - it's to respond, not react.",
            "A pause is not weakness.",
            "Under the anger there's usually a need worth naming.",
            "You can be firm and kind at the same time.",
            "Cool the body first; the words will be better.",
            "Winning the argument is not the same as being okay.",
        ],
        "exercises": [
            "Physiological sigh: inhale, top-up inhale, long slow exhale - repeat 3 times.",
            "Boundary script: 'When X happens, I feel Y. I need Z.' Write one sentence.",
            "Pause and cool: splash cold water or hold something cool for 30 seconds, then reassess.",
            "Draft, don't send: write the angry message in a notes app and wait 20 minutes.",
            "Discharge it: 2 minutes of fast walking, stairs, or push-ups.",
            "Name the need: respect, fairness, safety, or rest - which one feels crossed?",
            "Unclench: jaw, shoulders, fists - release each on a slow exhale.",
            "Rate it 0-10, breathe for a minute, rate it again.",
            "Ask: 'What outcome do I actually want here?' before you respond.",
        ],
        "tips": [
            "Delay the reply: draft it, don't send it, revisit in 20 minutes.",
            "Name the need under the anger (respect, safety, fairness).",
            "Move your body for 2 minutes to discharge adrenaline before speaking.",
            "Lower your volume on purpose; the body follows the voice.",
            "Use 'I' statements, not 'you always'.",
            "Step outside or into another room for 5 minutes if you can.",
            "Decide the one point you need to make, and drop the rest.",
            "Sleep on it if the stakes are high.",
        ],
    },
    "fear": {
        "videos": [
            {"title": "Fear to calm: breath and body", "url": _yt("fear to calm breathing body guided")},
            {"title": "Safe-place visualisation, guided", "url": _yt("safe place visualization guided meditation")},
            {"title": "Grounding for panic, follow along", "url": _yt("grounding technique for panic attack follow along")},
            {"title": "10-minute meditation for feeling unsafe", "url": _yt("10 minute meditation feeling unsafe reassurance")},
        ],
        "quotes": [
            "Courage is feeling fear and moving with care anyway.",
            "You can be uncertain and still be safe in this moment.",
            "Tiny steps are still forward.",
            "Fear shrinks when you name it out loud.",
            "You don't have to feel ready to begin.",
            "Most of what we fear never arrives.",
            "Your body is trying to protect you; thank it, then check the facts.",
            "One breath, then the next step.",
            "You are more resourced than the fear says.",
            "Safe enough is enough to start.",
        ],
        "exercises": [
            "Safety scan: name 3 signals that you're safe right now (place, body, support).",
            "If-then plan: 'If I start spiraling, then I will breathe and message someone.'",
            "Approach ladder: write the smallest next step (30 seconds) toward what you're avoiding.",
            "Orient to the room: slowly look left to right and name 5 objects.",
            "Long exhale: breathe out for a count of 6, in for 4, for 8 rounds.",
            "Fact-check the fear: 'What actually has to be true for the worst case?'",
            "Feet and back: feel the chair and floor holding you, 5 breaths.",
            "Call your support: even a text saying 'thinking of you' helps.",
            "Do one 2-minute version of the thing you're avoiding.",
        ],
        "tips": [
            "You're not alone - find what's controllable in the next 5 minutes.",
            "If it's not dangerous right now, you can practice staying present for 30 seconds.",
            "Treat thoughts like weather - notice them, don't obey them.",
            "Break the scary thing into the first tiny step only.",
            "Slow your exhale; it tells your body the threat has passed.",
            "Avoid caffeine and doomscrolling while the fear is high.",
            "Write the plan for 'if it goes wrong' so your brain can stop rehearsing it.",
            "Ask someone to be on standby while you take the step.",
        ],
    },
    "neutrality": {
        "videos": [
            {"title": "One-minute mindful check-in", "url": _yt("one minute mindful check in guided")},
            {"title": "Name the feeling: emotional awareness practice", "url": _yt("name the feeling emotional awareness practice")},
            {"title": "10-minute reset meditation", "url": _yt("10 minute reset meditation calm focus")},
            {"title": "Gentle focus / study music", "url": _yt("gentle focus study ambient music")},
        ],
        "quotes": [
            "Neutral is a valid state - use it to reset and choose intentionally.",
            "Clarity often arrives after a calm pause.",
            "Nothing urgent: just notice what you need next.",
            "A flat day is not a wasted day.",
            "You can use calm to prepare for the busy days.",
            "Not every moment needs a strong feeling.",
            "This is a good time to plant a small habit.",
            "Rest counts as productive.",
            "Curiosity is a fine thing to feel right now.",
            "Steady is underrated.",
        ],
        "exercises": [
            "One-minute check-in: 'What's my energy level (0-10)?' 'What do I need?'",
            "Micro-plan: choose 1 task, 1 break, 1 kindness for today.",
            "Mindful sip: drink water slowly and notice temperature and breath.",
            "Two-minute tidy: clear one small surface near you.",
            "Set one intention for the next hour and write it on a sticky note.",
            "Body scan from head to toe, 3 minutes, just noticing.",
            "Pick one thing you've been putting off and do the 5-minute version.",
            "Step outside for fresh air and 10 slow breaths.",
            "Write one line about how today is going so far.",
        ],
        "tips": [
            "If you feel 'nothing', try 'curious' instead of 'stuck'.",
            "Neutral is a good time to plan: pick a tiny goal and a tiny reward.",
            "If you're okay, protect it - take a small preventive break.",
            "Use the calm to prep something future-you will thank you for.",
            "Check in with one person you haven't spoken to in a while.",
            "Do a 10-minute version of a hobby you've been meaning to restart.",
            "Notice what a 'fine' day is made of so you can build more of them.",
        ],
    },
}
